import { Client } from "pg";
import { z } from "zod";
import { RecommendationStatus, ValidationStatus } from "../../generated/prisma/client";
import { prisma } from "../../db/prismaConnection";
import { assertSafeReadOnlyQuery, parseExplainResult } from "../rawquery/rawQuery";
import { log } from "../utils/logger";

type LlmRecommendation = {
  rewriteSql: string | null;
  indexDdl: string | null;
  llmExplanation: string;
};

const LlmRecommendationSchema = z.object({
  rewriteSql: z.string().nullable().optional(),
  indexDdl: z.string().nullable().optional(),
  llmExplanation: z.string().min(1).max(5000).optional(),
});

const INDEX_DDL_ALLOW = /^\s*create\s+index\s+[a-zA-Z0-9_]+\s+on\s+[a-zA-Z0-9_."]+\s*\(.+\)\s*;?\s*$/i;
const DDL_DENY = /\b(drop|alter|truncate|delete|update|insert|grant|revoke|copy|concurrently)\b/i;

const sanitizeLlmRecommendation = (value: LlmRecommendation): LlmRecommendation => {
  const rewriteSql = value.rewriteSql ? assertSafeReadOnlyQuery(value.rewriteSql) : null;
  let indexDdl: string | null = null;
  if (value.indexDdl) {
    const candidate = value.indexDdl.trim();
    if (DDL_DENY.test(candidate) || !INDEX_DDL_ALLOW.test(candidate)) {
      throw new Error("LLM index DDL failed allowlist/denylist guardrails.");
    }
    indexDdl = candidate.replace(/;+\s*$/, "");
  }
  return {
    rewriteSql,
    indexDdl,
    llmExplanation: value.llmExplanation,
  };
};

const askGeminiForRecommendation = async (
  sql: string,
  planJson: unknown,
): Promise<LlmRecommendation> => {
  const apiKey = process.env.GEMINI_API_KEY;
  const model = process.env.GEMINI_MODEL ?? "gemini-1.5-flash";
  if (!apiKey || apiKey.includes("<YOUR")) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  const prompt = `
You are a PostgreSQL performance expert.
Return ONLY JSON with keys: rewriteSql, indexDdl, llmExplanation.
- rewriteSql can be null
- indexDdl can be null
- Avoid CREATE INDEX CONCURRENTLY
- Keep behavior equivalent

SQL:
${sql}

EXPLAIN JSON:
${JSON.stringify(planJson)}
`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.1,
        responseMimeType: "application/json",
      },
    }),
  });

  if (!response.ok) {
    throw new Error(`Gemini request failed: ${await response.text()}`);
  }

  const payload = (await response.json()) as {
    candidates?: Array<{
      content?: { parts?: Array<{ text?: string }> };
    }>;
  };
  const content = payload.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!content) {
    throw new Error("Gemini returned empty response.");
  }

  const parsed = LlmRecommendationSchema.parse(JSON.parse(content));
  return {
    rewriteSql: typeof parsed.rewriteSql === "string" ? parsed.rewriteSql : null,
    indexDdl: typeof parsed.indexDdl === "string" ? parsed.indexDdl : null,
    llmExplanation: parsed.llmExplanation ?? "Generated by Gemini.",
  };
};

const fallbackHeuristicRecommendation = (
  sql: string,
  hasSeqScan: boolean,
): LlmRecommendation => {
  if (hasSeqScan) {
    return {
      rewriteSql: null,
      indexDdl: null,
      llmExplanation:
        "Detected sequential scan. Consider creating an index on frequently filtered columns in this query.",
    };
  }
  return {
    rewriteSql: sql,
    indexDdl: null,
    llmExplanation:
      "No obvious index recommendation from heuristic. Suggest reviewing joins, filters, and selected columns.",
  };
};

const validateRecommendation = async (recommendationId: string) => {
  const recommendation = await prisma.recommendation.findUnique({
    where: { id: recommendationId },
    include: { tenant: true, template: true },
  });
  if (!recommendation) throw new Error("Recommendation not found.");
  if (!recommendation.tenant.replicaUrl) {
    throw new Error("Tenant replicaUrl is required for replica validation.");
  }

  const client = new Client({ connectionString: recommendation.tenant.replicaUrl });
  await client.connect();
  try {
    await client.query("BEGIN");
    await client.query("SET LOCAL statement_timeout TO 15000");

    const baselineRaw = await client.query(
      `EXPLAIN (ANALYZE, FORMAT JSON) ${recommendation.template.rawSqlSample}`,
    );
    const baseline = parseExplainResult(baselineRaw.rows as unknown);

    if (recommendation.indexDdl) {
      const sanitized = sanitizeLlmRecommendation({
        rewriteSql: recommendation.rewriteSql,
        indexDdl: recommendation.indexDdl,
        llmExplanation: recommendation.llmExplanation,
      });
      if (sanitized.indexDdl) {
        await client.query(sanitized.indexDdl);
      }
    }

    const proposedSql = recommendation.rewriteSql ?? recommendation.template.rawSqlSample;
    const proposedRaw = await client.query(`EXPLAIN (ANALYZE, FORMAT JSON) ${proposedSql}`);
    const proposed = parseExplainResult(proposedRaw.rows as unknown);

    await client.query("ROLLBACK");

    const baselineMs = baseline.actualDurationMs;
    const proposedMs = proposed.actualDurationMs;
    const savingsPct = baselineMs > 0 ? ((baselineMs - proposedMs) / baselineMs) * 100 : 0;
    const passed = proposedMs < baselineMs;
    const confidenceScore = Math.max(0, Math.min(1, savingsPct / 100));

    const validationRun = await prisma.validationRun.create({
      data: {
        recommendationId,
        status: passed ? ValidationStatus.PASSED : ValidationStatus.FAILED,
        baselineDurationMs: baselineMs,
        proposedDurationMs: proposedMs,
        savingsPct,
        confidenceScore,
        replicaUsed: recommendation.tenant.replicaUrl,
      },
    });

    await prisma.recommendation.update({
      where: { id: recommendationId },
      data: { status: passed ? RecommendationStatus.VALIDATED : RecommendationStatus.REJECTED },
    });

    return validationRun;
  } catch (error) {
    try {
      await client.query("ROLLBACK");
    } catch {
      // ignore
    }
    const message = error instanceof Error ? error.message : "Unknown validation error";
    log("error", "recommendation_validation_error", {
      recommendationId,
      message,
    });
    const validationRun = await prisma.validationRun.create({
      data: {
        recommendationId,
        status: ValidationStatus.ERROR,
        errorMessage: message,
        replicaUsed: recommendation.tenant.replicaUrl,
      },
    });
    await prisma.recommendation.update({
      where: { id: recommendationId },
      data: { status: RecommendationStatus.REJECTED },
    });
    return validationRun;
  } finally {
    await client.end();
  }
};

export const generateAndValidateRecommendation = async (input: {
  tenantId: string;
  templateId?: string;
}) => {
  const template = input.templateId
    ? await prisma.queryTemplate.findFirst({
        where: { id: input.templateId, tenantId: input.tenantId },
        include: { explainPlans: { orderBy: { capturedAt: "desc" }, take: 1 } },
      })
    : await prisma.queryTemplate.findFirst({
        where: { tenantId: input.tenantId },
        orderBy: { impactScore: "desc" },
        include: { explainPlans: { orderBy: { capturedAt: "desc" }, take: 1 } },
      });

  if (!template) throw new Error("No query template found for recommendation generation.");
  const latestPlan = template.explainPlans[0];
  if (!latestPlan) throw new Error("No explain plan found for selected template.");

  let generated: LlmRecommendation;
  try {
    generated = sanitizeLlmRecommendation(
      await askGeminiForRecommendation(template.rawSqlSample, latestPlan.planJson),
    );
  } catch {
    generated = fallbackHeuristicRecommendation(template.rawSqlSample, latestPlan.hasSeqScan);
  }

  const recommendation = await prisma.recommendation.create({
    data: {
      tenantId: input.tenantId,
      templateId: template.id,
      llmModel: process.env.GEMINI_MODEL ?? "heuristic-v1",
      rewriteSql: generated.rewriteSql,
      indexDdl: generated.indexDdl,
      llmExplanation: generated.llmExplanation,
      status: RecommendationStatus.PENDING,
    },
  });

  const validationRun = await validateRecommendation(recommendation.id);
  const updatedRecommendation = await prisma.recommendation.findUnique({
    where: { id: recommendation.id },
  });

  return { recommendation: updatedRecommendation, validationRun };
};

export const validateRecommendationById = async (recommendationId: string) =>
  validateRecommendation(recommendationId);

